<a href="https://colab.research.google.com/github/ProNatalya/python/blob/main/demidovich_1_4_1_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Демидович Задача 1.5**
## Доказать, что:

## а) операция умножения вектора на число обладает следующим свойством:
## 1. 0 * a = $λ$ * $\textbf{0}$ = $\textbf{0}$
## 2. (λ1 * λ2) * a = λ1 * (λ2 * a)

# Решение 1.5 а) 1.

Пусть у нас есть вектор a = (a1, a2). Используя правило умножения вектора на число получим:
## 0 * a = 0 * (a1, a2) = (0 * a1, 0 * a2) = (0, 0) (при умножении любого числа на 0, получаем ноль).
## λ * $\textbf{0}$ = λ * (0, 0) = (λ * 0, λ * 0) = (0, 0)


In [ ]:
import numpy as np
a = np.array([[3, 7]])
v = np.zeros(2)
c = 5
print(0 * a) # в результате получаем нулевой вектор, ч.т.д.
print(c * v) # в результате получаем нулевой вектор, ч.т.д.


[[0 0]]
[0. 0.]


# Решение 1.5 а) 2.
## Для действий с векторами справедлив обычный алгебраический приоритет.
## Свойство ассоциативности по отношению к числам говорит о том, что результат операции не зависит от расстановки скобок.
## (a * b) * c = a * (b * c)
## Создадим произвольный вектор d.

In [ ]:
d = np.array([[1, 2]])
print((2 * 3) * d)
print(2 * (3 * d))
# и так получили равенство двух вычислений ч.т.д.

[[ 6 12]]
[[ 6 12]]


## б) операции сложения векторов и умножения их на числа связаны следующими двумя свойствами дистрибутивности:
## 1. $\textbf{λ(a1 + a2) = λa1 + λa2}$
## и
## 2. $\textbf{(λ1 + λ2)a = λ1a + λ2a}$

# Решение 1.5 б) 1.
## Рассмотрим первое свойство дистрибутивности: $\textbf{λ(a1 + a2) = λa1 + λa2}$.
## Определим, что означает сложение векторов и умножение вектора на число.
## Сложение векторов: Если у нас есть два вектора $\textbf{a1}$ и $\textbf{a2}$, то их сумма $\textbf{a1 + a2}$ определяется как вектор, у которого каждая компонента равна сумме соответствующих компонент векторов $\textbf{a1}$ и $\textbf{a2}$.
## Умножение вектора на число: Если у нас есть вектор $\textbf{a}$ и число $\textbf{λ}$, то произведение $\textbf{λa}$ определяется как вектор, у которого каждая компонента равна произведению соответствующей компоненты вектора $\textbf{a}$ на число $\textbf{λ}$.
## Теперь, чтобы доказать первое свойство дистрибутивности, применим определения сложения векторов и умножения вектора на число.
## Левая сторона равенства: $\textbf{λ(a1 + a2)}$.
# Это означает, что мы сначала складываем векторы $\textbf{a1}$ и $\textbf{a2}$, а затем умножаем полученную сумму на число $\textbf{λ}$.
## Правая сторона равенства: $\textbf{λa1 + λa2}$.
## Это означает, что мы сначала умножаем вектор $\textbf{a1}$ на число $\textbf{λ}$, затем умножаем вектор $\textbf{a2}$ на число $\textbf{λ}$, и затем складываем полученные произведения.
## Теперь сравним обе стороны равенства.
## Левая сторона равенства: $\textbf{λ(a1 + a2)}$.
# Зная, что сложение векторов определено как сумма соответствующих компонент векторов $\textbf{a1}$ и $\textbf{a2}$. Таким образом,$\textbf{λ(a1 + a2)}$ будет иметь компоненты, которые являются суммой соответствующих компонент векторов $\textbf{a1}$ и $\textbf{a2}$, умноженных на число $\textbf{λ}$.
## Правая сторона равенства: $\textbf{λa1 + λa2}$.
## Известно, что умножение вектора на число определено как произведение соответствующих компонент вектора $\textbf{a1}$ на число $\textbf{λ}$. Таким образом, $\textbf{λa1}$ будет иметь компоненты, которые являются произведением соответствующих компонент вектора $\textbf{a1}$ на число $\textbf{λ}$. Аналогично, $\textbf{λa2}$ будет иметь компоненты, которые являются произведением соответствующих компонент вектора $\textbf{a2}$ на число $\textbf{λ}$. Затем мы складываем полученные произведения.
## Таким образом, если мы сравним компоненты левой и правой стороны равенства, мы увидим, что они совпадают. Это означает, что $\textbf{λ(a1 + a2) = λa1 + λa2}$, и первое свойство дистрибутивности доказано.




In [ ]:
e1 = np.array([[4, 7]])
e2 = np.array([[1, 3]])
print(5*(e1 + e2))
print(5*e1 + 5*e2)

[[25 50]]
[[25 50]]


# Решение 1.5 б) 2.
## Теперь перейдем ко второму свойству дистрибутивности: $\textbf{(λ1 + λ2)a = λ1a + λ2a}$.
## Будем использовать аналогичный подход, определяя сложение чисел и умножение вектора на число.
## Сложение чисел: Если у нас есть два числа $\textbf{λ1}$ и $\textbf{λ2}$, то их сумма $\textbf{λ1 + λ2}$ определяется как число, которое получается при сложении $\textbf{λ1}$ и $\textbf{λ2}$.
## Умножение вектора на число: Если у нас есть вектор $\textbf{a}$ и число $\textbf{λ}$, то произведение $\textbf{λa}$ определяется как вектор, у которого каждая компонента равна произведению соответствующей компоненты вектора $\textbf{a}$ на число $\textbf{λ}$.
## Теперь, чтобы доказать второе свойство дистрибутивности, применим определения сложения чисел и умножения вектора на число.
## Левая сторона равенства:$\textbf{ (λ1 + λ2)a}$.
## Это означает, что мы сначала складываем числа $\textbf{λ1}$ и $\textbf{λ2}$, а затем умножаем полученную сумму на вектор $\textbf{a}$.
## Правая сторона равенства: $\textbf{λ1a + λ2a}$.
## Это означает, что мы сначала умножаем вектор $\textbf{a}$ на число $\textbf{λ1}$, затем умножаем вектор $\textbf{a}$ на число $\textbf{λ2}$, и затем складываем полученные произведения.
## Теперь проверим обе стороны равенства на совпадение.
## Левая сторона равенства: $\textbf{(λ1 + λ2)a}$.
## Так как сложение чисел определено как сумма $\textbf{λ1}$ и $\textbf{λ2}$. Таким образом, $\textbf{(λ1 + λ2)a}$ будет иметь компоненты, которые являются произведением соответствующих компонент вектора $\textbf{a}$ на сумму $\textbf{λ1}$ и $\textbf{λ2}$.
## Правая сторона равенства: $\textbf{λ1a + λ2a}$.
## Известно, что умножение вектора на число определено как произведение соответствующих компонент вектора $\textbf{a}$ на число $\textbf{λ1}$. Таким образом, $\textbf{λ1a}$ будет иметь компоненты, которые являются произведением соответствующих компонент вектора $\textbf{a}$ на число $\textbf{λ1}$. Аналогично, $\textbf{λ2a}$ будет иметь компоненты, которые являются произведением соответствующих компонент вектора $\textbf{a}$ на число $\textbf{λ2}$. Затем мы складываем полученные произведения.
## Таким образом, сравнивая компоненты левой и правой стороны равенства, видим, что они совпадают. Это означает, что $\textbf{(λ1 + λ2)a = λ1a + λ2a}$, и второе свойство дистрибутивности доказано.

In [ ]:
f1 = np.array([[4, 6]])
print((2 + 5)*f1)
print(2*f1 + 5*f1)

[[28 42]]
[[28 42]]


# **Демидович Задача 1.6**
## Доказать равенства:

## а) $\textbf{a} + $$\frac{1}{2}$$\textbf{(b - a)}$ = $\frac{1}{2}$$\textbf{(a + b)}$;


## Решение 1.6 а)
## $\textbf{a} + $$\frac{1}{2}$$\textbf{(b - a)}$ = $\frac{1}{2}$$\textbf{(a + b)}$;
## $\textbf{a} + $$\frac{1}{2}$$\textbf{b} - $$\frac{1}{2}$$\textbf{a}$ = $\frac{1}{2}$$\textbf{(a + b)}$;
## $\frac{1}{2}$$\textbf{(a + b)}$ = $\frac{1}{2}$$\textbf{(a + b)}$;
##  

## Таким образом равенство выполняется.
## Геометрический смысл этого равенства заключается в том, что вектор $\textbf{а}$ после сложения с половиной разности векторов $\textbf{b}$ и $\textbf{a}$ равен половине суммы векторов $\textbf{a}$ и $\textbf{b}$. Это означает, что вектор $\textbf{a}$ можно представить как среднее арифметическое векторов $\textbf{a}$ и $\textbf{b}$, где каждый вектор учитывается с весом $\frac{1}{2}$.


## Решение 1.6 б)
## $\textbf{a} - $$\frac{1}{2}$$\textbf{(a + b)}$ = $\frac{1}{2}$$\textbf{(a - b)}$;
## $\textbf{a} - $$\frac{1}{2}$$\textbf{a} - $$\frac{1}{2}$$\textbf{b}$ = $\frac{1}{2}$$\textbf{(a - b)}$;
## $\frac{1}{2}$$\textbf{(a - b)}$ = $\frac{1}{2}$$\textbf{(a - b)}$;
##  

## Таким образом равенство выполняется.
## Геометрический смысл этого равенства заключается в том, что вектор $\textbf{а}$ после вычитания половины суммы векторов $\textbf{a}$ и $\textbf{b}$ равен половине разности векторов $\textbf{a}$ и $\textbf{b}$. Это означает, что вектор $\textbf{a}$ можно представить как среднее арифметическое векторов $\textbf{a}$ и $\textbf{b}$, где каждый вектор учитывается с весом $\frac{1}{2}$.
