<a href="https://colab.research.google.com/github/ProNatalya/python/blob/main/demidovich_1_2_1_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Демидович Задача 1.2
Доказать равенства

## а) -a = (-1)a;


## Решение 1.2 а)
Чтобы доказать, что вектор -a равен -1*a, нам нужно показать, что их компоненты соответствуют друг другу.
Пусть у нас есть вектор a = (a1, a2, a3).
Тогда вектор -a будет иметь компоненты (-a1, -a2, -a3).
Вектор -1*a также будет иметь компоненты (-1*a1, -1*a2, -1*a3).
Мы можем заметить, что компоненты исходного вектора a и вектора -1*a идентичны, просто противоположны по знаку.
Таким образом, можно сделать вывод, что вектор -a = -1*a.

In [ ]:
import numpy as np
a = np.array([5, 2, 4])
b = -a
c = -1*a
print (a)
print(b)
print(c)

[5 2 4]
[-5 -2 -4]
[-5 -2 -4]


## б) a2 - a1 = a2 + (-a1);

## Решение 1.2 б)




### Для доказательства равенства векторов a2 - a1 = a2 + (-a1), мы можем использовать определение операций над векторами.
### Пусть a1 и a2 - два произвольных вектора.
### Тогда левая сторона равенства a2 - a1 можно записать как разность координат этих векторов:
a2 - a1 = (a2_1 - a1_1, a2_2 - a1_2, ..., a2_n - a1_n)
### Правая сторона равенства a2 + (-a1) представляет собой сумму вектора a2 и обратного вектора a1:
a2 + (-a1) = (a2_1 + (-a1_1), a2_2 + (-a1_2), ..., a2_n + (-a1_n))
### Теперь, чтобы доказать равенство, нам нужно показать, что каждая координата левой стороны равна соответствующей координате правой стороны.
### Рассмотрим произвольную координату i:
(a2_i - a1_i) = (a2_i + (-a1_i))
### Слева и справа находится одна и та же координата, поэтому равенство выполняется для всех координат.
### Исходя из этого, мы можем заключить, что векторы a2 - a1 и a2 + (-a1) равны.
### Таким образом, равенство a2 - a1 = a2 + (-a1) доказано.

In [ ]:
import numpy as np
a1 = np.array([8,5])
a2 = np.array([3,2])
print(a2[0] - a1[0])
print(a2[0] + (-a1[0]))
print(a2 - a1)
print(a2 + (-a1))

-5
-5
[-5 -3]
[-5 -3]


## в) a = |a|*a0, где a0 - орт вектора a, то есть вектор единичной длины, сонаправленный с вектором a (a !=0).


## Решение  1.2 в)
### Данное равенство a = |a|*a0 основывается на определении орта вектора и его длины. Орт вектора - это вектор, имеющий единичную длину и сонаправленный с данным вектором. Определим a как вектор в трехмерном пространстве a = [x, y, z].
### Длина вектора a, обозначаемая как |a|, может быть вычислена следующим образом: |a| = sqrt(x^2 + y^2 + z^2).
### Теперь, чтобы найти орт a0, мы делим каждую компоненту вектора a на его длину: a0 = [x/|a|, y/|a|, z/|a|].          
### Предположим, что |a| ≠ 0. Тогда мы можем записать a = |a|*a0 следующим образом: a = [x, y, z] |a|*a0 = |a|*[x/|a|, y/|a|, z/|a|] = [x, y, z].
### Таким образом, равенство a = |a|*a0 выполняется при условии, что длина вектора a не равна нулю (|a| ≠ 0).

In [ ]:
import numpy as np
a3 = np.array([5, 7, 9])
print(a3)
lenght_a3 = np.sqrt((a3*a3).sum())# np.linalal.norm(a)
print(lenght_a3)
a3_0 = a3/lenght_a3
print(a3_0)
print(lenght_a3 * a3_0)

[5 7 9]
12.449899597988733
[0.40160966 0.56225353 0.7228974 ]
[5. 7. 9.]


# Демидович Задача 1.3
В параллелепипеде ABCDA'B'C'D' векторы m, n, p представлены ребрами $\vec{AB}$, $\vec{AD}$, $\vec{AA'}$ соответственно. Построить векторы:

## а) m + n + p;

In [ ]:
from Ipython.display import Image
display(Image())

## Решение 1.3 а)

In [ ]:
import numpy as np
m = np.array([0, 4, 0])
n = np.array([8, 0, 0])
p = np.array([0, 0, 6])
print(m + n + p)

[8 4 6]


/content/demidovich_1_3_a.jpg

## б) $\frac{1}{2}m$ + $\frac{1}{2}n$ - p;

## Решение 1.3 б)

In [ ]:
print(m*0.5 + n*0.5 - p)

[ 4.  2. -6.]


/content/demidovich_1_3_b.jpg

## в) -m - n + $\frac{1}{2}p$

## Решение  1.3 в)

In [ ]:
print(-m - n + p*0.5)

[-8. -4.  3.]


/content/demidovich_1_3_v.jpg