<a href="https://colab.research.google.com/github/ProNatalya/python/blob/main/demidovich_7pg_1_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#  Демидович Задача 1.1
Доказать, что операция сложения векторов обладает следующими свойствами:



## a) a + 0 = a;

# Решение  1.1 а)
Для доказательства выражения "вектор a + 0 = a" нужно использовать определения и свойства  векторов.

Вектор a можно представить как сумму его компонент:a = (a1, a2, a3, ...,an) , где ai - компонента вектора a.

0 - нулевой вектор, у которого все компоненты равны нулю: 0 = (0, 0, 0, ..., 0).

Тогда, сложение  вектора a и нулевого вектора будет иметь вид:
a + 0 = (a1 + 0, a2 + 0, a3 + 0, ..., an) = a.

Таким образом доказано, что вектор a + 0 равен вектору a.

In [ ]:
import numpy as np
a = np.array([2, -4])
b = np.array([0, 0])
a + b

array([ 2, -4])

## б) a1 + a2 = a2 + a1 (коммутативность);

# Решение 1.1 б)
Для доказательства коммутативности сложения векторов a1 и a2, нужно использовать определения и свойства векторов.

Вектор a1 можно представить как сумму его компонент: a1 = (a11, a12, a13, ..., a1n), где a1i - i-я компонента вектора a1.

Аналогично, вектор a2 можно  представить как сумму его компонент: a2 = (a21, a22, a23, ..., a2n), где a2i - i-я компонента аектора a2.

Тогда, сложение  векторов a1 и a2 будет  иметь вид:
a1 + a2 = (a11 + a21, a12 + a22, a13 + a23, ..., a1n + a2n).

А сложение векторов a2 и a1 будет  иметь вид:
a2 + a1 = (a21 + a11, a22 + a12, a23 + a13, ..., a2n + a1n).

Так как сложение чисел коммутативно, то каждая компонента суммы будет  равна в обоих случаях.

Таким образом, доказано, что векторы a1 + a2 и a2 + a1 равны поэлементно и, следовательно , коммутативны.

In [ ]:
a1 = np.array([7, -4, 3])
a2 = np.array([3, -8, 5])
print(a1 + a2)
print(a2 + a1)

[ 10 -12   8]
[ 10 -12   8]


# в) a1 + (a2 + a3) = (a1 + a2) + a3 (ассоциативность);

# Решение 1.1 в)
Вектор a1 можно  представить как сумму его компонент: a1 = (a1_1, a1_2, a1_3, ..., a1n), где a1_i-я компонента вектора a1.

Аналогично, вектор a2 можно  представить как сумму его компонент: a2 = (a2_1, a2_2, a2_3, ..., a2_n), где a2_i - i-я компонента вектора a2.

Также, вектор a3 можно  представить как сумму его компонент: a3 = (a3_1, a3_2, a3_3,..., a3_n), где a3_i - i-я компонента вектора a3.

Тогда, сложение векторов a2 и a3 будет иметь вид:
a2 + a3 = (a2_1 + a3_1, a2_2 + a3_2, a2_3 + a3_3, a2n + a3_n).

И сложение векторов a1 и (a2 + a3) будет  иметь вид:
a1 + (a2 + a3) = (a1_1 + (a2_1 + a3_1 ), a1_2 + (a2_2 + a3_2), a1_3 +(a2_3 + a3_3, ..., a1_n + (a2_n + a3_n)).

А также, сложение векторов (a1 + a2) и a3 будет  иметь вид:
(a1 + a2) + a3 = ((a1_1 + a2_1) + a3_1, (a1_2 + a2_2) + a3_2, (a1_3 + a2_3) + a3_3,..., (a1_n + a2_n) + a3_n).

Так как сложение чисел ассоциативно, то каждая компонета суммы будет равна в обоих случаях.

Таким рбразом доказано , что векторы a1 + (a2 + a3) и (a1 + a2) + a3 равны.


In [ ]:
a1 = np.array([2, 3, 7])
a2 = np.array([7, 5, -2])
a3 = np.array([0, 2, 5])
print(a1 + (a2 + a3))
print((a1 + a2) + a3)

[ 9 10 10]
[ 9 10 10]


# г) $\forall$a $\exists$! b (a + b = 0) (вектор b называется вектором, противоположным вектору a, и обозначается символом -a);

# Решение 1.1 г)


In [ ]:
import numpy as np
a = np.array ([2, 6])
b = -a
a + b

array([0, 0])

# д) $\forall$a1, a2 $\exists$! a3 (a1 + a3 = a2) (вектор a3 называется разностью векторов a2 и a1 и обозначается символом a2 - a1).

# Решение 1.1 д)

In [ ]:
a1 = np.array([5, 8])
a2 = np.array([2,6])
a3 = a2 - a1
a1 + a3 # = a2


array([2, 6])