<a href="https://colab.research.google.com/github/ProNatalya/python/blob/main/stepic_vec_alg_np_2_1_2_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Вход: 2 целых числа, разделенные пробелом.
# Выход: массив NumPy из этих чисел.
import numpy as np
a,b = map(int, input().split(' '))
v = np.array([a, b])
print(v)
# 3 2

3 2
[3 2]


In [ ]:
v=np.array(input().split(), dtype=int)
print(v)


3 2
[3 2]


In [ ]:
# Вход: 3 вещественных числа, разделенные пробелом.
# Выход: массив NumPy из этих чисел.
# Sample Input:
# 3.3 3 2.2
# Sample Output:
# [3.3 3.  2.2]
a,b,c = map(float, input().split(' '))
v = np.array([a, b, c])
print(v)

3.3 3 2.2
[3.3 3.  2.2]


In [ ]:
print(np.array(input().split(), float))


3.3 3 2.2
[3.3 3.  2.2]


In [ ]:
# Вход: в первой строчке шесть чисел координаты точки начала и конца первого
# вектора x1, y1, z1 и x2, y2, z2,
# во второй строчке координаты для второго вектора.

# Выход: True, если вектора равны, иначе False.
# Sample Input:
# 1 2 3 3 4 5
# -3 3 2 -1 5 4
# Sample Output:
# True
x1, x2, x3, y1, y2, y3 = map(int, input().split())
x1_2, x2_2, x3_2, y1_2, y2_2, y3_2 = map(int, input().split())
list1 = ([x1, x2, x3, y1, y2, y3])
list2 = ([x1_2, x2_2, x3_2, y1_2, y2_2, y3_2])
list1_1 = (list1[5]-list1[2], list1[4]-list1[1],list1[3]-list1[0])
#print(list1_1)
list2_1 = (list2[5]-list2[2], list2[4]-list2[1],list2[3]-list2[0])
#print(list2_1)
if list1_1 == list2_1:
    print('True')
else:
    print('False')

1 2 3 3 4 5
-3 3 2 -1 5 4
True


In [ ]:
a, b = [np.array(list(map(int, input().split()))) for _ in range(2)]

print(np.all(a[3:] - a[:3] == b[3:] - b[:3]))

In [ ]:
arr1, arr2 = input().split(), input().split()
arr1 = np.array(arr1[3:], dtype=int) - np.array(arr1[:3], dtype=int)
arr2 = np.array(arr2[3:], dtype=int) - np.array(arr2[:3], dtype=int)
print((arr1 == arr2).all())

1 2 3 3 4 5
-3 3 2 -1 5 4
True


In [ ]:
a = np.array(list(map(float, input().split())))
b = np.array(list(map(float, input().split())))
c = a - b
print(all(c[:3]==c[3:]))

## Модуль и норма вектора

Эта формула выражает расстояние от начала координат до точки, заданной вектором a. Также модуль вектора иногда называют L2-нормой или евклидовой нормой.

В1:Что такое модуль вектора в трехмерном пространстве?
О1:Длина вектора, выраженная в единицах измерения осей координат

## Вычисление модуля вектора в NumPy

NumPy (Numerical Python) - это библиотека языка программирования Python для работы с многомерными массивами и матрицами. Она предоставляет множество функций для выполнения различных операций над массивами, включая вычисление модуля вектора.

Для вычисления модуля вектора в NumPy можно воспользоваться функцией linalg.norm(). Она принимает на вход массив и возвращает его модуль. Давайте рассмотрим пример:

In [ ]:
# Создаем вектор
v = np.array([3, 4, 5])

# Вычисляем модуль вектора
norm_v = np.linalg.norm(v)

print(norm_v)# 7.0710678118654755

7.0710678118654755


Функция np.linalg.norm() может принимать несколько параметров. Например, мы можем указать размерность массива, для которого нужно вычислить модуль. По умолчанию функция вычисляет модуль для всего массива, но если мы хотим вычислить модуль только для строк или столбцов, мы можем указать размерность с помощью параметра axis.

Давайте рассмотрим несколько примеров:

In [ ]:
# Создаем двумерный массив
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Вычисляем модуль каждой строки матрицы
norm_rows = np.linalg.norm(A, axis=1)

print(norm_rows) # [ 3.74165739  8.77496439 13.92838828]

[ 3.74165739  8.77496439 13.92838828]


## Другие нормы вектора

Кроме евклидовой нормы, рассмотренной ранее, существуют другие меры нормы векторов.

Например, L1 норма, также известная как манхэттенское расстояние или сумма модулей, является одним из популярных способов измерения расстояния между двумя векторами в линейной алгебре.

Для вектора X, L1 норма определяется как сумма модулей его элементов:

L1 норма обладает несколькими интересными свойствами, включая то, что она устойчива к выбросам, что может быть полезно при обработке данных с шумом или выбросами.

L1 норма часто используется в машинном обучении, например, в регрессии LASSO (Least Absolute Shrinkage and Selection Operator), где она используется для регуляризации модели путем штрафования больших значений коэффициентов регрессии. Она также может быть использована для отбора признаков и сокращения размерности данных.

Кроме того, L1 норма может использоваться для решения задачи линейного программирования, таких как задачи поиска максимального потока в сети, где она используется для нахождения оптимального пути через граф, минимизируя общую сумму стоимости проезда по каждому ребру.

Свойства L1-нормы: см.учебник

Функция np.linalg.norm() также может принимать параметр ord, который определяет порядок нормы. По умолчанию параметр ord=None, что означает вычисление Евклидовой нормы. Если параметр ord=1, то будет вычислена L1-норма.

In [ ]:
# Создаем вектор
v = np.array([3, -1, 4])

# Вычисляем L1-норму вектора
norm_l1 = np.linalg.norm(v, ord=1)

print(norm_l1) # 8.0

8.0


L-бесконечность норма (также называемая инфинитезимальной или максимальной нормой) - это еще один способ измерения "величины" вектора в линейной алгебре. Она определяется как максимальное абсолютное значение координат вектора.

Пусть у нас есть вектор v с n координатами:

v = [x1, x2, ..., xn]

L-бесконечность норма вектора v определяется следующим образом:

|v|inf = max(|x1|, |x2|, ..., |xn|)

Таким образом, L-бесконечность норма вектора - это максимальное абсолютное значение его координат.

Давайте рассмотрим несколько примеров вычисления L-бесконечность нормы вектора с помощью NumPy:

In [ ]:
# Создаем вектор
v = np.array([3, -1, 4])

# Вычисляем L-бесконечность норму вектора
norm_inf = np.linalg.norm(v, ord=np.inf)

print(norm_inf) # 4.0

4.0


В этом примере мы создали вектор v с координатами [3, -1, 4] и вычислили его L-бесконечность норму с помощью функции np.linalg.norm() и параметра ord=np.inf. Результат вычисления - 4.0.

Свойства L-бесконечность нормы: см.учебник

L-бесконечность норма широко применяется в различных областях, включая машинное обучение, оптимизацию и анализ данных. Например, она может быть использована для вычисления максимальной ошибки в регрессионной модели или для оценки влияния выбросов в данных на результаты статистических анализов.

# Task_1

О, великий Космический Дух! Я, скромный знаток математики, призываю тебя открыть мне тайны Линейной Алгебры и помочь мне в решении этой головоломки. Дано натуральное чисел n, и вектор v с координатами [0.5, 0.25, 0.125, ..., 0.5^n]. Мне необходимо вычислить L1 норму этого вектора, чтобы проникнуться знаниями и мудростью этого мира. О, великий Космический Дух, дай мне силу и знания, чтобы я мог произнести заклинание и раскрыть тайну этой задачи. И я произнесу: "Открой мне путь к знанию, о могучий Космический Дух! Дай мне силу преодолеть трудности этой задачи! Позволь мне посчитать L1 норму вектора v и получить знание, которое откроет мне новые горизонты познания". И великий Космический Дух послал мне свой благословенный свет, который осветил мой путь к знанию. И я, во имя Космического Духа, вычислил L1 норму вектора v, и она равна ... И я почувствовал, как знание и мудрость заполнили мое сердце, и стал чувствовать себя более мудрым и могучим

In [ ]:
# Sample Input 1:
# 4
# Sample Output 1:
# 0.9375
# Sample Input 2:
# 25
# Sample Output 2:
# 0.9999999701976776
# Sample Input 3:
# 1000000
# Sample Output 3:
# 1.0
import numpy as np
v = np.array([0.5**i for i in range(1, int(input()) + 1)])
print(np.linalg.norm(v, ord = 1))

4
0.9375


In [ ]:
n = int(input())

print(1 - 0.5 ** n)

4
0.9375


In [ ]:
n = int(input())
v = 0.5 ** np.arange(1, n+1)
print(np.linalg.norm(v, ord=1))

4
0.9375


In [ ]:
n = int(input())
arr = np.array([0.5**i for i in range(1,n+1)])
l1_norm = np.linalg.norm(arr,ord=1)
print(l1_norm)

4
0.9375


# Task_2

Некогда, в заброшенной деревне, существовало проклятие, которое превратило жителей в камень. Но однажды, из-за великой силы магии, они ожили и превратились в массив arr, состоящий из множества векторов. Все векторы были замечательны, но их сила была неясна и неизвестна, как и причина их возрождения. И тогда появился голос из тьмы, призывающий измерить норму каждого вектора в массиве, используя L2 норму, чтобы определить их силу и выяснить их истинное назначение. Во имя тьмы и магии, задача была принята. Но чтобы выполнить ее, необходимо было пройти через множество испытаний и преодолеть опасности, которые таятся в самом сердце массива. Мысли были смутны, а страх захватывал сердце. Но зловещий голос из тьмы был неумолим и задача должна быть выполнена. Без колебаний была направлена магическая сила, чтобы измерить L2 норму каждого вектора, и каждый раз, когда измерение было завершено, зловещий голос ревел в темноте: "Норма измерена! Вектор пройден!". И в итоге, когда все испытания были пройдены, была получена строка из чисел, выражающих L2 норму каждого вектора, и она была возвращена в темноту, чтобы определить истинное предназначение массива и рассеять туманы неведения.

Двумерный массив arr с векторами, записанными в каждой его строке уже существует необходимо вычислите норму каждого вектора и вывести их через пробел в строку.

In [1]:
import numpy as np
arr = [[1, 2, 3], [4, 5, 6]]
norm_rows = np.linalg.norm(arr, axis = 1,ord=2)
result = ' '.join(map(str, norm_rows))
print(result)


3.7416573867739413 8.774964387392123


In [2]:
print(*np.linalg.norm(arr, axis=1)) # * - распаковка списка с помощью *

3.7416573867739413 8.774964387392123


In [3]:
print(*np.linalg.norm(arr,axis=1,ord=2))

3.7416573867739413 8.774964387392123
